name: Development Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - development-deployment

jobs:
  deploy_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Code linting
        run: |
          npm install
          npm install --global @forge/cli
          forge settings set usage-analytics true
          forge lint -e development

      - name: Install Dependencies and Forge CLI
        run: |
          npm install
          npm install --global @forge/cli
          forge settings set usage-analytics true

      - name: Build UI inside static folder
        working-directory: static/frontend
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy Forge To Development Environment
        run: forge deploy -e development
