name: Verify code using ESLint and Prettier
on:
  push:
    branches:
      - '**'
      - '!production-deployment'
      - '!development-deployment'
      - '!uat'
      - '!main'
      - '!develop'

  pull_request:
    branches:
      - '**'
      - '!production-deployment'
      - '!development-deployment'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump GitHub Env Variables GITHUB_REF
        run: echo ${GITHUB_REF}

      - name: Dump GitHub Env Variables GITHUB_REF_NAME
        run: echo ${GITHUB_REF_NAME}

      - name: Dump GitHub Env Variables GITHUB_BASE_REF
        run: echo ${GITHUB_BASE_REF}

      - name: Dump GitHub Env Variables GITHUB_HEAD_REF
        run: echo ${GITHUB_HEAD_REF}

      - name: Install packages
        run: npm ci

      - name: Prettier
        run: npm run prettier:check

      - name: ESLint
        run: npm run lint:check
#      - name: Forge Linter
#        run: |
#          npm install --global @forge/cli
#          forge settings set usage-analytics true
#          forge lint
