name: Verify code using ESLint and Prettier
on:
  push:
    branches:
      - main
      - develop
      - uat

  pull_request:
    branches:
      - main
      - develop
      - uat

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Prettier
        run: npm run prettier:check

      - name: ESLint
        run: npm run lint:check
