name: Production Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - production-deployment

jobs:
  deploy_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump GitHub Env Variables GITHUB_REF
        run: echo ${GITHUB_REF}

      - name: Dump GitHub Env Variables GITHUB_REF_NAME
        run: echo ${GITHUB_REF_NAME}

      - name: Dump GitHub Env Variables GITHUB_BASE_REF
        run: echo ${GITHUB_BASE_REF}

      - name: Dump GitHub Env Variables GITHUB_HEAD_REF
        run: echo ${GITHUB_HEAD_REF}

      - name: Check Code linting
        run: |
          npm install
          npm install --global @forge/cli
          forge settings set usage-analytics true
          forge lint -e production

      - name: Install Dependencies and Forge CLI
        run: |
          npm install
          npm install --global @forge/cli
          forge settings set usage-analytics true

      - name: Build UI inside static folder
        working-directory: static/frontend
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy Forge To Production Environment
        run: forge deploy -e production
