name: Pull Request Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-pull-request-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check If Pull Request Branch Is Allowed
        run: |
          if [[ ( ! startsWith(github.base_ref, 'hotfix/') && ! ${GITHUB_BASE_REF} = uat ) && ${GITHUB_HEAD_REF} = main ]]; 
          then
            echo "Error: Pull request for main branch must come from 'uat' or 'hotfix/' branch"
            exit 1
          fi
